### ISSUE TITLE
There is no python2 on OSX (it has python2.7)

### ISSUE THREAD

**Issue by mejedi** [tarantool/test-run#15] opened 2015-10-12 14:54 UTC
Test-run.py fails to run osx, because it doesn't have python2 (specified in test-run via schebang).

I suggest changing schebang to python2.7 instead of python2.

**Comment by Totktonada** [comment] 2020-09-24 22:46
I hope it'll be resolved by #20.

**Comment by ligurio** [comment] 2021-02-14 08:18
Duplicate of #20.

**Closed** 2021-02-14 08:18 UTC
Labels: bug, teamE
